spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database_url:jdbc:postgresql://localhost:5432/auth_service}
    username: ${database_username:postgres}
    password: ${database_password:THsF*3858}
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: ${server_port:8082}