version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  mail-service:
    build: 
      context: ./mail-service
    expose:
      - 8081
    environment:
      - server_port=8081
      - sender_gmail={email}
      - sender_app_password={app_password}
    depends_on:
      - rabbitmq
volumes:
  rabbitmq-data: