version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  mail-service:
    build: 
      context: ./mail-service
    expose:
      - 8081
    environment:
      - server_port=8081
      - sender_gmail={sender_email}
      - sender_app_password={app_password}
      - rabbitmq_host=rabbitmq
      - rabbitmq_port=5672
      - rabbitmq_username=admin
      - rabbitmq_password=admin
    depends_on:
      - rabbitmq
volumes:
  rabbitmq-data: