spring:
  application:
    name: mail-service
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${sender_gmail}
    password: ${sender_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${server_port:8081}