spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${sender_gmail}
    password: ${sender_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
